In [1]:
import torch

In [2]:
import torch.nn.functional as F

In [3]:
import math

In [4]:
X = torch.randn(3, 4)

In [5]:
X

tensor([[ 0.4429,  0.1565, -0.1563,  0.6542],
        [ 0.9923,  0.5027,  0.2441, -0.3815],
        [ 0.3501, -0.1387, -0.7541, -1.0343]])

In [6]:
d_model = 4

In [7]:
d_k = 4

In [8]:
W_q = torch.randn(d_model, d_k)

In [9]:
W_k = torch.randn(d_model,d_k)

In [10]:
W_v = torch.randn(d_model,d_k)

In [11]:
Q = torch.matmul(X,W_q)

In [12]:
K = torch.matmul(X,W_k)

In [14]:
V = torch.matmul(X,W_v)

In [15]:
scores = torch.matmul(Q,K.transpose(-2,-1)) / math.sqrt(d_k)

In [17]:
scores

tensor([[ 0.1436, -1.1523,  1.1047],
        [-0.2941, -0.6053,  1.8576],
        [ 0.0666, -1.5731, -3.5730]])

In [18]:
attention_weights = F.softmax(scores,dim=-1)

In [19]:
attention_weights

tensor([[0.2572, 0.0704, 0.6724],
        [0.0968, 0.0709, 0.8323],
        [0.8195, 0.1590, 0.0215]])

In [20]:
values = torch.matmul(attention_weights,V)

In [21]:
values

tensor([[ 0.3896,  0.5103, -0.1237,  0.5858],
        [ 0.3695,  0.7527, -0.1704,  0.4480],
        [ 0.3697, -0.3983, -0.0385,  1.2062]])