In [27]:
from datasets import load_dataset

In [28]:
from transformers import AutoTokenizer,DataCollatorWithPadding

In [29]:
raw_datasets = load_dataset('glue','mrpc')

In [30]:
checkpoint = 'bert-base-uncased'

In [31]:
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

In [32]:
def tokenize_function(examples):
    return tokenizer(examples['sentence1'],examples['sentence2'],truncation=True)

In [33]:
tokenized_datasets = raw_datasets.map(tokenize_function,batched=True)

In [34]:
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

In [35]:
from transformers import TrainingArguments,Trainer

In [36]:
training_args = TrainingArguments('test-trainer')

In [37]:
from transformers import AutoModelForSequenceClassification

In [38]:
model = AutoModelForSequenceClassification.from_pretrained(checkpoint,num_labels=2)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [39]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['validation'],
    data_collator=data_collator,
    tokenizer=tokenizer,
)

/tmp/ipykernel_80249/3811618646.py:1: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(


In [40]:
trainer.train()

TrainOutput(global_step=1377, training_loss=0.34636432257093375, metrics={'train_runtime': 51.004, 'train_samples_per_second': 215.748, 'train_steps_per_second': 26.998, 'total_flos': 405114969714960.0, 'train_loss': 0.34636432257093375, 'epoch': 3.0})

In [41]:
predictions = trainer.predict(tokenized_datasets['validation'])

In [42]:
predictions.predictions

array([[-3.1064043 ,  3.4399467 ],
       [ 2.163486  , -2.3814237 ],
       [ 1.1824319 , -1.5088292 ],
       [-3.1106052 ,  3.498166  ],
       [ 2.3967626 , -2.778603  ],
       [-3.131073  ,  3.4976354 ],
       [-2.8935065 ,  3.1695678 ],
       [-3.1522481 ,  3.5414724 ],
       [-3.0793886 ,  3.378613  ],
       [-3.1863713 ,  3.5295537 ],
       [-3.157893  ,  3.499002  ],
       [ 2.3483682 , -2.6061885 ],
       [ 2.553897  , -2.7705116 ],
       [-2.763959  ,  3.1537683 ],
       [-3.2000659 ,  3.5097167 ],
       [-1.7739825 ,  1.9087607 ],
       [-3.1971085 ,  3.5343673 ],
       [ 1.3864024 , -1.2085787 ],
       [-3.1931908 ,  3.5137691 ],
       [ 1.5308689 , -1.317504  ],
       [ 2.2294788 , -2.493667  ],
       [-2.405734  ,  2.7426472 ],
       [ 2.4353356 , -2.6697302 ],
       [-3.1104777 ,  3.430233  ],
       [-3.1443367 ,  3.478773  ],
       [-2.564361  ,  2.7466786 ],
       [-2.3504663 ,  2.6088214 ],
       [-3.2090194 ,  3.5308762 ],
       [-3.155674  ,

In [43]:
predictions.label_ids

array([1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,

In [44]:
predictions.metrics

{'test_loss': 0.6668211817741394,
 'test_runtime': 0.5499,
 'test_samples_per_second': 741.978,
 'test_steps_per_second': 92.747}

In [45]:
import numpy as np

In [46]:
preds = np.argmax(predictions.predictions,axis=-1)

In [47]:
preds

array([1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,

In [48]:
import evaluate

metric = evaluate.load("glue", "mrpc")
metric.compute(predictions=preds, references=predictions.label_ids) 

{'accuracy': 0.8553921568627451, 'f1': 0.8970331588132635}

In [49]:
def compute_metrics(eval_preds):
    metric = evaluate.load('glue','mrpc')
    logits,labels = eval_preds
    predictions = np.argmax(logits,axis=-1)
    return metric.compute(predictions=predictions,references=labels)

In [50]:
training_args = TrainingArguments("test-trainer", eval_strategy="epoch", save_strategy="epoch", load_best_model_at_end=True, metric_for_best_model="accuracy",report_to="wandb")

In [51]:
model = AutoModelForSequenceClassification.from_pretrained(checkpoint,num_labels=2)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [52]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['validation'],
    data_collator=data_collator,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
)

/tmp/ipykernel_80249/2179171129.py:1: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(


In [53]:
trainer.train()

TrainOutput(global_step=1377, training_loss=0.376033331400775, metrics={'train_runtime': 74.8789, 'train_samples_per_second': 146.957, 'train_steps_per_second': 18.39, 'total_flos': 405114969714960.0, 'train_loss': 0.376033331400775, 'epoch': 3.0})